### ISSUE TITLE
recording into array - next step is same as current step?

### ISSUE THREAD

**Issue by tastez** [mgunyho/PdArray#22] opened 2023-11-08 23:04 UTC
I got a problem where i am trying to capture a sequence into Array but can never do it since one step will always be wrong in the sequence. Both play and Record play heads are being controlled by Ministep. Toggling on and off record at the right time should capture the sequence correctly, for example an 8 step melody. However when I am at step 8 and it has been recorded, step 1 is also set to the value of step 8 and needs to be recorded over. So you end up with this leading wrong input all the time.
Hope that makes sense.

**Comment by mgunyho** [comment] 2023-11-09 06:25
I don't understand exactly how you're doing the recording, could you show a screenshot of your patch? Or preferably just a minimal patch which contains nothing more than an example of this behavior, using only VCV built-in modules in addition to PdArray, so I can test it myself.

Are you saying that when the record playhead is at the position of the last step, it's also modifying the first step? Or that you are incrementing the step when it's at the end, at the same time as turning the recording off? For the second case, I think it could be fixed by adding a small  delay to the increment trigger, for example using the falling edge or delay outputs of [VCV Gates](https://library.vcvrack.com/Fundamental/Gates)

**Comment by tastez** [comment] 2023-11-09 11:01
hi - im just using a trigger to increment the Ministep. Delaying the trigger for the recording position does indeed work sort of (sometimes glitches) but to find the length of the delay is pretty annoying since its tempo relative. Increasing length of of the trigger into a gate didn't help, so i left it out of the test patches. You'll need to click the button to reset the counters so stuff lines up. The idea is to not need extra modules to delay the recording head.
[patches.zip](https://github.com/mgunyho/PdArray/files/13307243/patches.zip)

**Comment by mgunyho** [comment] 2023-11-15 19:09
Hi, sorry for the delay. Looks like the issue is that the value you are recording goes directly from the random sampler output to the REC IN, while the input to REC POS is delayed by one sample because it goes through the Ministep (in VCV Rack there is a delay of one sample for each cable). So there is an instant of time where the Random Sampler's output `X1` is already outputting its next value but the output of Ministep has not yet been incremented.

This can be avoided by adding a delay to the signal path of `X1` by routing it through some module that does nothing, for example VCV Mutes, or you can find several modules in the Library that allow choosing the number of samples to delay if you want more than one. Here's an example where the top array shows the problem and the bottom the fixed behavior with Mutes:


https://github.com/mgunyho/PdArray/assets/20118130/825cee37-ce33-4c46-8357-4268bf13b7d8


Let me know if you need some more help, otherwise this issue can be closed.

**Closed as completed** 2023-11-15 20:50 UTC
